INSERT INTO TOPPINGS (TOPPING_ID, NAME, PRICE) VALUES (1, 'sonka', 150);
INSERT INTO TOPPINGS (TOPPING_ID, NAME, PRICE) VALUES (2, 'szalami', 150);

INSERT INTO PIZZAS (PIZZA_ID, NAME, PRICE, SIZE, IMAGEURL) VALUES (1, 'sonkas pizza', 1500, 32, 'http://luckypizzeria.hu/product_image/rectangle_640/50.png');
INSERT INTO PIZZAS (PIZZA_ID, NAME, PRICE, SIZE, IMAGEURL) VALUES (2, 'szalamis pizza', 1500, 32, 'http://luckypizzeria.hu/product_image/rectangle_640/24.png');

INSERT INTO PIZZA_TOPPING (PIZZA_ID, TOPPING_ID) VALUES (1, 1);
INSERT INTO PIZZA_TOPPING (PIZZA_ID, TOPPING_ID) VALUES (2, 2);

INSERT INTO USERS (USER_ID, ADDRESS, EMAIL, PASSWORD, PHONE, ROLE, USERNAME) VALUES (1, 'Szolnok', 'fos@fos.hu', '1234', '012512', 'ADMIN', 'mroncsi');


